import { and, asc, eq, gte, lte, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { entries, habits } from "../../../db/schema";
const defaults = [["Прочитать 20 страниц","📖",20,"стр.",1],["Встать в 06:00","☀️",1,"раз",2],["Лечь спать в 23:00","🌙",1,"раз",3],["Прочитать 5 намазов","🤲",5,"намазов",4],["Работа над ресёрчем","✍️",60,"мин",5],["Работа над GitHub","⌘",60,"мин",6],["Тренировка на турнике","⚡",60,"мин",7]] as const;
function fail(error:unknown){console.error(error);return Response.json({error:"Не удалось сохранить данные. Попробуйте ещё раз."},{status:500})}
export async function GET(request:Request){try{const db=getDb(),url=new URL(request.url),from=url.searchParams.get("from")??new Date().toISOString().slice(0,10),to=url.searchParams.get("to")??from;const existing=await db.select({count:sql<number>`count(*)`}).from(habits);if(!existing[0]?.count)await db.insert(habits).values(defaults.map(([title,emoji,target,unit,sortOrder])=>({title,emoji,target,unit,sortOrder})));const habitRows=await db.select().from(habits).where(eq(habits.active,true)).orderBy(asc(habits.sortOrder),asc(habits.id));const entryRows=await db.select().from(entries).where(and(gte(entries.date,from),lte(entries.date,to)));return Response.json({habits:habitRows,entries:entryRows})}catch(e){return fail(e)}}
export async function POST(request:Request){try{const b=await request.json() as Record<string,unknown>,title=String(b.title??"").trim(),target=Number(b.target??1);if(!title||!Number.isFinite(target)||target<=0)return Response.json({error:"Проверьте название и цель."},{status:400});const [habit]=await getDb().insert(habits).values({title,target,emoji:String(b.emoji??"✨"),unit:String(b.unit??"раз"),kind:b.kind==="meteor"?"meteor":"habit",scheduledDate:b.kind==="meteor"?String(b.scheduledDate??new Date().toISOString().slice(0,10)):null,sortOrder:Number(b.sortOrder??99)}).returning();return Response.json({habit},{status:201})}catch(e){return fail(e)}}
export async function PATCH(request:Request){try{const b=await request.json() as Record<string,unknown>,db=getDb();if(b.action==="progress"){const habitId=Number(b.habitId),date=String(b.date),value=Math.max(0,Number(b.value));await db.insert(entries).values({habitId,date,value}).onConflictDoUpdate({target:[entries.habitId,entries.date],set:{value}});return Response.json({ok:true})}await db.update(habits).set({title:String(b.title??"").trim(),emoji:String(b.emoji??"✨"),target:Math.max(.01,Number(b.target??1)),unit:String(b.unit??"раз"),scheduledDate:b.scheduledDate?String(b.scheduledDate):null}).where(eq(habits.id,Number(b.id)));return Response.json({ok:true})}catch(e){return fail(e)}}
export async function DELETE(request:Request){try{const id=Number(new URL(request.url).searchParams.get("id"));await getDb().update(habits).set({active:false}).where(eq(habits.id,id));return Response.json({ok:true})}catch(e){return fail(e)}}
